# Generated by Django 6.1 on 2026-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='anonimo',
            field=models.BooleanField(default=True),
        ),
    ]
