# Generated by Django 6.1 on 2026-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampara', '0002_depoimento_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='descricao',
            field=models.CharField(max_length=10000),
        ),
    ]
